export const HTTP_ERROR_CODE = Object.freeze({
    "401_UNAUTHORIZED": "401_UNAUTHORIZED",
    "403_FORBIDDEN": "403_FORBIDDEN",
    "400_BAD_REQUEST": "400_BAD_REQUEST",
    "404_NOT_FOUND": "404_NOT_FOUND",
    "409_CONFLICT": "409_CONFLICT",
    "500_INTERNAL_SERVER_ERROR": "500_INTERNAL_SERVER_ERROR",
});

export const ERROR_TYPE = Object.freeze({
    UNAUTHORIZED: "UNAUTHORIZED",
    BAD_DATA: "BAD_DATA",
    ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
    CONFLICT: "CONFLICT",
    FORBIDDEN: "FORBIDDEN",
});

export const TOKEN_TYPE = Object.freeze({
    ACCESS_TOKEN: "ACCESS_TOKEN",
    SESSION_TOKEN: "REFRESH_TOKEN",
});
